// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzdbGucqHaju-hPK30KluuxrjapEgoB8',
    appId: '1:116608033536:web:677bef42eec189677dc9e5',
    messagingSenderId: '116608033536',
    projectId: 'autosms-7bc30',
    authDomain: 'autosms-7bc30.firebaseapp.com',
    databaseURL: 'https://autosms-7bc30-default-rtdb.firebaseio.com',
    storageBucket: 'autosms-7bc30.firebasestorage.app',
    measurementId: 'G-LLSX2ZWSE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8mpEhmsRFbTbrpofP2fdlbRmTfMrZe3E',
    appId: '1:116608033536:android:2555596d033da0977dc9e5',
    messagingSenderId: '116608033536',
    projectId: 'autosms-7bc30',
    databaseURL: 'https://autosms-7bc30-default-rtdb.firebaseio.com',
    storageBucket: 'autosms-7bc30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQaZbDC3r_wnAs799drsMeuXIJPx1f8qM',
    appId: '1:116608033536:ios:a304a12cb10d803d7dc9e5',
    messagingSenderId: '116608033536',
    projectId: 'autosms-7bc30',
    databaseURL: 'https://autosms-7bc30-default-rtdb.firebaseio.com',
    storageBucket: 'autosms-7bc30.firebasestorage.app',
    iosBundleId: 'com.example.autoSms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQaZbDC3r_wnAs799drsMeuXIJPx1f8qM',
    appId: '1:116608033536:ios:a304a12cb10d803d7dc9e5',
    messagingSenderId: '116608033536',
    projectId: 'autosms-7bc30',
    databaseURL: 'https://autosms-7bc30-default-rtdb.firebaseio.com',
    storageBucket: 'autosms-7bc30.firebasestorage.app',
    iosBundleId: 'com.example.autoSms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhzdbGucqHaju-hPK30KluuxrjapEgoB8',
    appId: '1:116608033536:web:15ecbf96c34bf7dc7dc9e5',
    messagingSenderId: '116608033536',
    projectId: 'autosms-7bc30',
    authDomain: 'autosms-7bc30.firebaseapp.com',
    databaseURL: 'https://autosms-7bc30-default-rtdb.firebaseio.com',
    storageBucket: 'autosms-7bc30.firebasestorage.app',
    measurementId: 'G-V24M9GCQZQ',
  );
}
